package handler

import (
	_ "github.com/AwesomeXjs/iq-progress/docs" // docs is generated by Swag CLI

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

const (
	version1 = "/v1"
	baseBath = "/api"

	sendPath       = "/send"
	operationsPath = "/operations/:id"
	depositPath    = "/deposit"
)

// InitRoutes initializes all the routes for the application.
func (h *Handler) InitRoutes(server *echo.Echo) {
	server.GET("/swagger/*", echoSwagger.WrapHandler)

	api := server.Group(baseBath)
	{
		v1 := api.Group(version1)
		{
			v1.POST(sendPath, h.Send)
			v1.GET(operationsPath, h.GetLastOperations)
			v1.POST(depositPath, h.MakeDeposit)
		}
	}
}
