name: CI

on:
    push:
        branches:
            - main


jobs:
    build-app:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.23

        - name: Build application
          run: go build -v ./...
    tests:
      name: Test Service layer
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'
            cache: false

        - name: Run tests for Auth service
          run: |
            go test ./... -v