basePath: /
definitions:
  model.DepositRequest:
    properties:
      amount:
        example: 1000
        type: integer
      user_id:
        example: 1
        type: integer
    type: object
  model.Operation:
    properties:
      amount:
        type: integer
      from_user_id:
        type: integer
      id:
        type: integer
      receiver_username:
        type: string
      sender_username:
        type: string
      to_user_id:
        type: integer
      transaction_date:
        type: string
      type:
        type: string
    type: object
  model.SendRequest:
    properties:
      amount:
        example: 100
        type: integer
      receiver:
        example: 2
        type: integer
      sender:
        example: 1
        type: integer
    type: object
  schema.GetOperationsSchema:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Operation'
        type: array
      request:
        example: /api/v1/send
        type: string
      time:
        example: "2023-01-01 00:00:00"
        type: string
      title:
        example: status
        type: string
    type: object
  schema.OperationSuccessSchema:
    properties:
      data:
        example: 1000
        type: integer
      request:
        example: /api/v1/send
        type: string
      time:
        example: "2023-01-01 00:00:00"
        type: string
      title:
        example: status
        type: string
    type: object
  utils.Body:
    properties:
      data: {}
      request:
        type: string
      time:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API Server for money transfer
  title: Banking API
  version: "1.0"
paths:
  /api/v1/deposit:
    post:
      consumes:
      - application/json
      description: make deposit for user
      operationId: MakeDeposit
      parameters:
      - description: deposit info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.DepositRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.OperationSuccessSchema'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Body'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Body'
      summary: MakeDeposit
      tags:
      - User
  /api/v1/operations/{id}:
    get:
      consumes:
      - application/json
      description: get last operations for user
      operationId: GetLastOperations
      parameters:
      - description: user id
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GetOperationsSchema'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Body'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Body'
      summary: GetLastOperations
      tags:
      - User
  /api/v1/send:
    post:
      consumes:
      - application/json
      description: send money to another user
      operationId: Send
      parameters:
      - description: data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.SendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.OperationSuccessSchema'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Body'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Body'
      summary: Send
      tags:
      - User
swagger: "2.0"
